<?php

use Illuminate\Database\Seeder;
use App\Choice;

class ChoicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Choice::insert([
    		[ 'unit_id' => 1 , 'question_id' => 1 , 'content' => 'クロマニョン人' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 1 , 'content' => '北京原人' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 1 , 'content' => 'ジャワ原人' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 1 , 'content' => 'アウストラロピテクス' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 2 , 'content' => '土器を使って料理や食料の保存をするようになった' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 2 , 'content' => '仲間とのやりとりで言葉を使うようになった' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 2 , 'content' => '木の実や植物を集め、食料とするようになった' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 2 , 'content' => '火を使うようになった' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 3 , 'content' => 'インダス文明' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 3 , 'content' => 'エジプト文明' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 3 , 'content' => '中国文明' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 3 , 'content' => 'メソポタミア文明' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 4 , 'content' => '甲骨文字' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 4 , 'content' => 'くさび形文字' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 4 , 'content' => 'ヒエログリフ' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 4 , 'content' => 'アルファベット' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 5 , 'content' => 'モヘンジョ＝ダロ' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 5 , 'content' => 'ハンムラビ法典' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 5 , 'content' => '太陽暦' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 5 , 'content' => '60進法' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 6 , 'content' => 'イスラム教' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 6 , 'content' => '仏教' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 6 , 'content' => 'キリスト教' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 6 , 'content' => 'ユダヤ教' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 7 , 'content' => '秦' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 7 , 'content' => '殷' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 7 , 'content' => '漢（前漢）' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 7 , 'content' => '周' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 8 , 'content' => '万里の長城' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 8 , 'content' => '焚書坑儒' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 8 , 'content' => '度量衡の統一' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 8 , 'content' => '楽浪郡の設置' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 9 , 'content' => '新羅' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 9 , 'content' => '伽耶（加羅）' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 9 , 'content' => '高句麗' , 'is_answer' => 1 ],
    		[ 'unit_id' => 1 , 'question_id' => 9 , 'content' => '百済' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 10 , 'content' => '百済' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 10 , 'content' => '高句麗' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 10 , 'content' => '隋' , 'is_answer' => 0 ],
    		[ 'unit_id' => 1 , 'question_id' => 10 , 'content' => '新羅' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 11 , 'content' => '登呂遺跡' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 11 , 'content' => '岩宿遺跡' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 11 , 'content' => '三内丸山遺跡' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 11 , 'content' => '吉野ヶ里遺跡' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 12 , 'content' => '青銅器' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 12 , 'content' => '高床式倉庫' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 12 , 'content' => '鉄器' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 12 , 'content' => '土偶' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 13 , 'content' => 'クリ' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 13 , 'content' => 'ナウマンゾウ' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 13 , 'content' => 'イノシシ' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 13 , 'content' => 'ハマグリ' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 14 , 'content' => 'もともと男の王が治めていたが、戦乱が続いた後、卑弥呼という女王が国を治めるようになった。' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 14 , 'content' => '中国の歴史書「後漢書東夷伝」に邪馬台国について書かれた記述がある。' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 14 , 'content' => '30ほどの国を従えていた。' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 14 , 'content' => '身分の区別があり、奴隷もいた。' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 15 , 'content' => '大仙古墳' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 15 , 'content' => '稲荷山古墳' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 15 , 'content' => '五色塚古墳' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 15 , 'content' => '江田船山古墳' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 16 , 'content' => '鉄剣' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 16 , 'content' => '石包丁' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 16 , 'content' => '銅鏡' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 16 , 'content' => '埴輪' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 17 , 'content' => '須恵器' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 17 , 'content' => '仏教' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 17 , 'content' => '弥生土器' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 17 , 'content' => '儒教' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 18 , 'content' => '魏' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 18 , 'content' => '呉' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 18 , 'content' => '秦' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 18 , 'content' => '漢' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 19 , 'content' => '新羅' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 19 , 'content' => '高句麗' , 'is_answer' => 1 ],
    		[ 'unit_id' => 2 , 'question_id' => 19 , 'content' => '伽耶' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 19 , 'content' => '百済' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 20 , 'content' => 'インド' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 20 , 'content' => '中国' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 20 , 'content' => '東南アジア' , 'is_answer' => 0 ],
    		[ 'unit_id' => 2 , 'question_id' => 20 , 'content' => '朝鮮半島' , 'is_answer' => 1 ],
		]);
    }
}
